### ISSUE TITLE
您好，是否有本地运行配置的教程呢？

### ISSUE THREAD

**Issue by ShiChenbin** [Ghost-LZW/fake-oj-be#1]
如题。很抱歉打扰您，期待您的回复。

**Comment by Ghost-LZW** [comment]
* 用sql文件初始化表
* 修改application.yaml中url 用户名 密码 redis端口为本地信息
* 使用Maven进行构建 或在idea中运行

已更新至readme

**Comment by ShiChenbin** [comment]
谢谢！
